### PR TITLE
Move to BusIO

### PR DESCRIPTION
**Pull request by caternuson**
Fix for #33 

Changed to using `BusIO.SPIDevice`, which cleans things up and fixes the issue.

### CODE REVIEW

**Comment by caternuson** [comment]
Huh. No CI? Feels weird. PR was tested:

**UNO**
```
MAX31855 test
Internal Temp = 27.50
C = 26.75
Internal Temp = 27.50
C = 26.50
Internal Temp = 27.50
C = 26.75
Internal Temp = 27.50
C = 27.00
Internal Temp = 27.50
C = 31.75
```

**Feather M0**
```
MAX31855 test
Internal Temp = 27.56
C = 26.75
Internal Temp = 27.56
C = 26.75
Internal Temp = 27.56
C = 31.00
Internal Temp = 27.56
C = 32.00
```

**Comment by ladyada** [comment]
wanna add actions CI next?

**Comment by caternuson** [comment]
sure. i'll give it a try.

**Comment by ladyada** [comment]
* git pull
* create new branch actionsci
* switch to branch actionsci
* cp Adafruit_ILI9341/.github -> repo
* in githubci.yml update PRETTYNAME
* in repo add GH_REPO_TOKEN to secrets
* move any travis library installs to library.properties "depends=" list
* delete .travis.yml
* within repo run: clang-format.exe -i *.cpp *.h
* bump library.properties
* change readme.md badge to (update reponame)

Build Status

**Pull request merged**
